### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Get all Students
GET http://localhost:8080/api/v1/students

### Get student by ID
GET http://localhost:8080/api/v1/students/7


### Post
POST http://localhost:8080/api/v1/students
Content-Type: application/json

{
  "name": "Jacob",
  "course": "CSC 400",
  "semester": "Fall 2025",
  "email": "erick@gmail.com"
}

### update a student
PUT http://localhost:8080/api/v1/students/7
Content-Type: application/json

{
  "name": "Frederick",
  "course": "CSC 400",
  "semester": "Spring 2027",
  "email": "brayanFred@gmail.com"
}

### update student attribute
PATCH http://localhost:8080/api/v1/students/7
Content-Type: application/json

{
  "name": "Jose Ramos"
}

### Delete Student
DELETE http://localhost:8080/api/v1/students/1

