spring.application.name=student_api

# Direct the application to the database and connect using credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/students
spring.datasource.username=erickgonzalez
spring.datasource.password=springboot123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true