spring.application.name=student_api

# Direct the application to the database and connect using credentials
spring.datasource.url=jdbc:postgresql://localhost:5432/students
spring.datasource.username=erickgonzalez
spring.datasource.password=springboot123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging Configuration
logging.file.name=logs/student-api.log
logging.level.root=INFO
logging.level.com.erick.student_api.service=DEBUG
logging.level.com.erick.student_api.exception=WARN

logging.logback.rollingpolicy.file-name-pattern=logs/student-api.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=100MB